-- reset sequence
ALTER TABLE admins MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- password: password123!
INSERT INTO admins (username, password) VALUES ('administrator', 'icqpMV7H/CrwpF8VyQtyVhBdoY+5tWhGE3DjJcAKcFRDUM0QOpu686oiRa/gn3FK');
-- deleted admin
INSERT INTO admins (username, password, deleted_at) VALUES ('deletedAdministrator', 'icqpMV7H/CrwpF8VyQtyVhBdoY+5tWhGE3DjJcAKcFRDUM0QOpu686oiRa/gn3FK', SYSDATE);
