spring:
  application:
    name: cinema

  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

