spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    com.uos.dsd.cinema: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace 

jwt:
  secretKey: "cinemaAppSecretKey12345678901234567890123456789012"
  accessTokenExpirationMs: 1800000  # 30분
  refreshTokenExpirationMs: 3600000  # 1시간
