spring:
  application:
    name: cinema

  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

jasypt:
  encryptor:
    password: ${CINEMA_JASYPT_KEY}
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64