spring:
  application:
    name: cinema

  datasource:
    url: ${SPRING_DATASOURCE_URL:ENC(/M2hEe79yHtAzPUbLOgpfI3w4VJ/EKj4FHfakRfTkNFvR729PV3SfnU3/GJtCaLlMr620LtGurK5TTy7MEeZ/qE2mXXVnmLB8Y9XP05az3k=)}
    username: ${SPRING_DATASOURCE_USERNAME:ENC(fcpsWaj+w8F4DbdbCiDOQH8+Lryd2VSCgjNiHg+rTy2H2uo1/Stk6oXlBBcHOsUT)}
    password: ${SPRING_DATASOURCE_PASSWORD:ENC(P2MuRIwh5SN1aT6DiQQrHr6CLdprOxRywOkkn9kA+m7AoaBcDDudtVPp0FNQl1cKGb4uH0YqXV/9Xh4EewSOTg==)}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

jasypt:
  encryptor:
    password: ${CINEMA_JASYPT_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

jwt:
  secretKey: ${JWT_SECRET_KEY:ENC(JbohwUOPO8ZJ2VZxNVEayPVBrfVME0VpLbnATIq7rw5jaOpmfxU7NvpB+hbzrkjROUPlYGTfmBrBj4CZRPaVPzDqxdHGRmEjhSLd/R0b6/pQWzyHttJQYzLAsH2AjUfO)}
  accessTokenExpirationMs: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:ENC(ReHHfs6Ux8nhCuZpWHZEjjNgc7zNpGdRxu9dU5W2Wi9qAAznNPw8hPa6kt6xrJly)}
  refreshTokenExpirationMs: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:ENC(71mzjSrTlhBgHDJ7i0lc9cOxpXw0819Q9nqI7//ckPmc+p4BUQcZLpxnpx5uC32l)}

server:
  host: localhost
  port: 8080
