spring:
  application:
    name: cinema

  datasource:
    url: jdbc:oracle:thin:@oracle:1521/CINEMA
    username: cinema
    password: cinema
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

jasypt:
  encryptor:
    password: ${CINEMA_JASYPT_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

jwt:
  secretKey: ENC(e7ndeI+tpOJOGFRbIFgT6t8gKGJwsZcNGSqi1ErlAu2z9JeJ36Jm/642rc/3jG3Di8eJ8o7Aa752tirB4JM0IPOSx7CYpuNwQQXE7361zBY=)
  accessTokenExpirationMs: ENC(372jdGhP8cHUJS8T9HKKqA/RAA0hVFNljoPhoxY+FqT/PyAmAiNYmrjipG4TAm6o)
  refreshTokenExpirationMs: ENC(k6jL/gcI6YUnJpKmsad6Zb+BfwbrmzhqqJJmEhKK9iLgbv6z7wknBBdeeEthmm3s)

storage:
  root:
    path: ./storage
