services:
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD
      - APP_USER
      - APP_USER_PASSWORD
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/oracle@localhost/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network

  backend:
    build: ../
    image: backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - CINEMA_JASYPT_KEY
      - JWT_SECRET_KEY
      - JWT_ACCESS_TOKEN_EXPIRATION_MS
      - JWT_REFRESH_TOKEN_EXPIRATION_MS
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SERVER_PORT
      - SERVER_HOST
      - SPRING_SQL_INIT_MODE
      - SPRING_SQL_INIT_PLATFORM
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS
      - SPRING_SQL_INIT_DATA_LOCATIONS
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
