services:
  oracle:
    image: gvenzl/oracle-free
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=cinema
      - APP_USER_PASSWORD=cinema
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/oracle@localhost/XEPDB1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - app-network

  backend:
    build: ../
    image: backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - CINEMA_JASYPT_KEY=XwZ#]=r9nErAe*)M!1!yi,Wxz*Ga^Fa~
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=cinema
      - SPRING_DATASOURCE_PASSWORD=cinema
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SERVER_PORT=8080
      - SERVER_HOST=localhost
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_PLATFORM=oracle
      - SPRING_SQL_INIT_SCHEMA_LOCATIONS=classpath:db/migration/V1__init.sql
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath:db/data.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
