-- 상영 유형
CREATE TABLE screen_types (
    type         VARCHAR2(50),
    icon_url     VARCHAR2(255),
    price        NUMBER(10) NOT NULL,

    PRIMARY KEY (type)
);

-- 상영관
CREATE TABLE theaters (
    id           NUMBER,
    name         VARCHAR2(50) UNIQUE NOT NULL,
    layout       CLOB NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT check_layout CHECK (layout IS JSON)
);

-- 상영관 좌석
CREATE TABLE theater_seats (
    theater_id   NUMBER,
    seat_number  CHAR(3) NOT NULL,
    is_available CHAR(1) DEFAULT 'Y',

    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP,

    PRIMARY KEY (theater_id, seat_number),
    FOREIGN KEY (theater_id) REFERENCES theaters(id) ON DELETE CASCADE,
    CONSTRAINT check_theater_seat_available CHECK (is_available IN ('Y', 'N'))
);

-- 상영관 제공 상영유형
CREATE TABLE theater_screen_types (
    theater_id   NUMBER,
    screen_type  VARCHAR2(50),

    PRIMARY KEY (theater_id, screen_type),
    FOREIGN KEY (theater_id) REFERENCES theaters(id) ON DELETE CASCADE,
    FOREIGN KEY (screen_type) REFERENCES screen_types(type) ON DELETE CASCADE
);

-- 장르
CREATE TABLE genres (
    name         VARCHAR2(50),
    description  VARCHAR2(255),
    image_url    VARCHAR2(255),

    PRIMARY KEY (name)
);

-- 고객 유형
CREATE TABLE customer_types (
    type            VARCHAR2(20),
    discount_amount NUMBER(10) DEFAULT 0 NOT NULL,

    PRIMARY KEY (type)
);

-- 은행
CREATE TABLE banks (
    name            VARCHAR2(50),
    logo_url        VARCHAR2(255),
    discount_amount NUMBER(10) DEFAULT 0 NOT NULL,

    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,

    PRIMARY KEY (name)
);

-- 카드사
CREATE TABLE card_companies (
    name            VARCHAR2(50),
    logo_url        VARCHAR2(255),
    discount_amount NUMBER(10) DEFAULT 0 NOT NULL,

    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,

    PRIMARY KEY (name)
);

-- 관리자
CREATE TABLE admins (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    username VARCHAR2(50) UNIQUE NOT NULL,
    password CHAR(64) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    PRIMARY KEY (id)
);

-- 고객
CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    user_type VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);

-- 회원 테이블
CREATE TABLE members (
    customer_id NUMBER,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password CHAR(64) NOT NULL,
    name VARCHAR2(20) NOT NULL,
    phone VARCHAR2(20) NOT NULL UNIQUE,
    birth_date DATE,
    profile_image_url VARCHAR2(255),

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- 비회원
CREATE TABLE guests (
    customer_id NUMBER,
    name        VARCHAR2(50) NOT NULL,
    phone       VARCHAR2(20) NOT NULL,
    birth_date  DATE,
    password    CHAR(64) NOT NULL,

    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- 감독 테이블
CREATE TABLE directors (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    name        VARCHAR2(100) NOT NULL,
    photo_url   VARCHAR2(255),

    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP,

    PRIMARY KEY (id)
);

-- 배우 테이블
CREATE TABLE actors (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    name        VARCHAR2(100) NOT NULL,
    photo_url   VARCHAR2(255),

    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP,

    PRIMARY KEY (id)
);

-- 영화
CREATE TABLE movies (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    title           VARCHAR2(100) NOT NULL,
    synopsis        VARCHAR2(255),
    running_time    NUMBER(10) NOT NULL,
    rating          VARCHAR2(20) DEFAULT 'ALL' NOT NULL,
    poster_urls     CLOB DEFAULT '[]' NOT NULL,
    release_date    DATE,
    distributor     VARCHAR2(50),
    director_id     NUMBER,
    cumulative_bookings NUMBER(10) DEFAULT 0 NOT NULL,

    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP,

    PRIMARY KEY (id),
    FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE SET NULL,
    CONSTRAINT check_rating CHECK (rating IN ('ALL', 'TWELVE', 'FIFTEEN', 'EIGHTEEN'))
);

-- 영화 통계 테이블
CREATE TABLE movie_statistics (
    statistic_date      DATE NOT NULL,
    movie_id            NUMBER NOT NULL,
    cumulative_bookings NUMBER NOT NULL,

    PRIMARY KEY (statistic_date, movie_id),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
);

-- 영화 제공 상영유형
CREATE TABLE movie_screen_types (
    movie_id    NUMBER NOT NULL,
    screen_type VARCHAR2(50) NOT NULL,

    PRIMARY KEY (movie_id, screen_type),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    FOREIGN KEY (screen_type) REFERENCES screen_types(type) ON DELETE CASCADE
);

-- 영화 장르 테이블
CREATE TABLE movie_genres (
    movie_id    NUMBER NOT NULL,
    genre_name  VARCHAR2(50) NOT NULL,

    PRIMARY KEY (movie_id, genre_name),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_name) REFERENCES genres(name) ON DELETE CASCADE
);

-- 영화 출연진 테이블
CREATE TABLE movie_casts (
    movie_id        NUMBER NOT NULL,
    actor_id        NUMBER NOT NULL,
    role            VARCHAR2(50),
    casting_type    VARCHAR2(20),

    PRIMARY KEY (movie_id, actor_id),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    FOREIGN KEY (actor_id) REFERENCES actors(id) ON DELETE CASCADE
);

-- 상영 일정
CREATE TABLE screenings (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    movie_id            NUMBER NOT NULL,
    theater_id          NUMBER NOT NULL,
    screen_type         VARCHAR2(20) NOT NULL,
    start_time          TIMESTAMP NOT NULL,
    duration            NUMBER(10) NOT NULL,

    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at          TIMESTAMP,

    PRIMARY KEY (id),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    FOREIGN KEY (theater_id) REFERENCES theaters(id) ON DELETE CASCADE,
    FOREIGN KEY (screen_type) REFERENCES screen_types(type) ON DELETE CASCADE
);

-- 예매 내역 테이블
CREATE TABLE reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    customer_id NUMBER,
    screening_id NUMBER,
    status VARCHAR2(20) DEFAULT 'PROGRESS' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- snapshot
    seat_snapshot CLOB DEFAULT '[]' NOT NULL,
    customer_count_snapshot CLOB DEFAULT '[]' NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    FOREIGN KEY (screening_id) REFERENCES screenings(id) ON DELETE SET NULL
);

-- 예매 좌석 테이블
CREATE TABLE reservation_seats (
    screening_id NUMBER NOT NULL,
    theater_id NUMBER NOT NULL,
    seat_number CHAR(3) NOT NULL,
    reservation_id NUMBER NOT NULL,

    PRIMARY KEY (screening_id, theater_id, seat_number),
    FOREIGN KEY (screening_id) REFERENCES screenings(id) ON DELETE CASCADE,
    FOREIGN KEY (theater_id, seat_number) REFERENCES theater_seats(theater_id, seat_number) ON DELETE CASCADE,
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
);

-- 예매 고객 유형별 인원 수 테이블
CREATE TABLE reservation_customer_counts (
    id NUMBER,
    customer_type VARCHAR2(20) NOT NULL,
    count NUMBER(10) NOT NULL,

    PRIMARY KEY (id, customer_type),
    FOREIGN KEY (id) REFERENCES reservations(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_type) REFERENCES customer_types(type) ON DELETE CASCADE
);

-- 결제 내역 테이블
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    reservation_id NUMBER NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    payment_method VARCHAR2(20) NOT NULL,
    approval_number VARCHAR2(50),
    original_price NUMBER(10) NOT NULL,
    discount_amount NUMBER(10) NOT NULL,
    final_price NUMBER(10) NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
);

-- 환불 내역 테이블
CREATE TABLE refunds (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    payment_id NUMBER NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    approval_number VARCHAR2(50),
    price NUMBER(10) NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
);

-- 포인트 테이블
CREATE TABLE point_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    payment_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    point NUMBER(10) NOT NULL,
    total_point NUMBER(10) NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);